name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${BRANCH}" # シェルコマンドからの参照
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }} # envコンテキスト経由
  print:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - env:
          BRANCH: override
        run: echo "${BRANCH}" # step内でオーバーライドされたenv